export const ADD_STOCK_SYMBOL = 'ADD_STOCK_SYMBOL';
export const REMOVE_STOCK_SYMBOL = 'REMOVE_STOCK_SYMBOL';
export const QUOTE_DATA = 'QUOTE_DATA';
export const EXPAND_STOCK_DETAILS = 'EXPAND_STOCK_DETAILS';
export const COLLAPSE_STOCK_DETAILS = 'COLLAPSE_STOCK_DETAILS';

// composing new stock
export const NEW_STOCK_SYMBOL_CHANGED = 'NEW_STOCK_SYMBOL_CHANGED';

// settings
export const TICKER_WIDTH = 'TICKER_WIDTH';
